//body component for seed.jsx
import { faker } from "@faker-js/faker";
import _ from "lodash";
import { useCallback, useContext, useEffect, useState } from "react";
import { Button } from "../../../../components";
import { WizardContext } from "../../sign-up";

//TODO: Should Download button have an error popup?
//should value/text be handled by state
//TODO: copy to clipboard - should we use react-copy-to-clipboard library?
//currently writing from scratch
//TODO: how does body work with context in step?

export const Body = ({ text, setText }) => {
  // Get updateSeed
  const { updateSeedPhrases } = useContext(WizardContext);

  // These are seed phrases generated by the library
  // Triggered on page loading with use effect from SDK
  // At this step, they can still be overwritten (not in context yet)
  const [seedPhrases, setSeedPhrases] = useState([]);

  // Generate Seed Phrases
  useEffect(() => {
    setSeedPhrases(
      Array.from({ length: 12 }, () =>
        faker.word.adjective()
      ) /** Sdk.generateSeedPhrases()  */
    );
  }, []);

  // Regenerate Seed Phrases
  const regenerateSeedPhrases = useCallback(() => {
    setSeedPhrases(
      Array.from({ length: 12 }, () =>
        faker.word.adjective()
      ) /** Sdk.generateSeedPhrases()  */
    );
  }, []);

  // Update Context store when seedPhrases changes
  useEffect(() => {
    updateSeedPhrases(seedPhrases);
  }, [seedPhrases]);

  // Copy to clipboard function
  // Get seeds from store
  const copy = async () => {
    await navigator.clipboard.writeText(text);
    alert(text);
  };

  // Download to text function
  const downloadTextFile = () => {
    const element = document.createElement("a");
    const file = new Blob([document.getElementById("input").value], {
      type: "text/plain",
    });
    element.href = URL.createObjectURL(file);
    element.download = "myFile.txt";
    document.body.appendChild(element);
    element.click();
  };

  return (
    <>
      <h3 className="pb-12px m-0 fw-bold text-white text-opacity-90 fs-18px">
        Save your seed phrase
      </h3>

      <div>
        {seedPhrases.map((phrase) => (
          <p key={_.uniqueId("seed-phrase-")}>{phrase}</p>
        ))}
      </div>
      <Button onClick={regenerateSeedPhrases}>Regenerate</Button>

      <p className="fs-14px fw-normal mt-auto text-center lh-sm mb-32px">
        Write down your seed phrase in a secure place. If you loose it without
        setting up peers to restore it, you'll loose access to your account
        forever
      </p>
      <div className=" d-flex gap-16px">
        <Button onClick={copy}>Copy</Button>
        <Button onClick={downloadTextFile}>Download</Button>
      </div>
    </>
  );
};
